// Static App Router segments. Unknown error-route segments are masked.
export const staticSegments = [
    'about-us',
    'add-college',
    'attendance-manager',
    'branch',
    'callback',
    'cgpa-calculator',
    'collections',
    'community',
    'contact-us',
    'front-page-generator',
    'groups',
    'leaderboard',
    'lost-found',
    'notes',
    'opportunities',
    'payment',
    'privacy-policy',
    'products',
    'profile',
    'pyqs',
    'quicknotes',
    'refund-policy',
    'resources',
    'seniors',
    'sign-in',
    'sign-up',
    'solution',
    'store',
    'support',
    'syllabus',
    'terms-and-conditions',
    'tools',
    'videos',
    'wallet',
] as const;
